name: CI

on: push

jobs:
  build:
    name: Build and Test
    runs-on: macos-15
    steps:
    - name: Checkout Code
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
